var phrases = [
  'big data',
  'blockchain',
  'bimodal',
  'smart nation',
  'analytics',
  'cloud',
  'machine learning',
  'innovation',
  'new technologies',
  'agile',
  'API',
  'digitalisation',
  'security',
  'compliance',
  'best practices',
  'digital transformation',
  'technology stack',
  'future-ready',
  'future-proof',
  'cyber threats',
  'user-centric',
  'as-a-service',
  'container',
  'automate',
  'audit and deviations',
  'assurance'
];
