var phrases = [
  'One shot one kill',
  'Tanking',
  'Balls want to drop',
  'Every mother father son',
  'Cool shit',
  'Not funny not funny it\'s true',
  'Don\'t laugh lah, it\'s true',
  'Muck around',
  'The important thing in life',
  'Guai guai',
  'Tambah',
  'Tank',
  'No choice',
  'Means got problem',
  'There\'s the truth and then there\'s the brutal truth',
  'There is vision and then there is reality',
  'These people are not stooopid ok?',
  '&lt;cluck&gt;',
  'The general point is',
  'The point is',
  'The thing is that',
  'Can or not?',
  'At some level',
  'Sai understand?',
  'Stupid or not?',
  'We talk offline',
  '\u597D\u4E0D\u597D',
  'Dun liddat lah',
  'You think they hire me because I handsome issit?',
  'Auntie-killer',
  'Timeout timeout timeout!',
  'Jaw drop',
  'The moral of the story is'
];

