var phrases = [
  '&lt;cluck&gt;',
  'At some level',
  'Auntie-killer',
  'Balls want to drop',
  'By the power vested in me, I hereby...',
  'Can or not?',
  'Cool shit',
  'Die die',
  'Do good shit',
  'Do some stupid shit',
  'Don\'t laugh lah, it\'s true',
  'Dun liddat lah',
  'Every mother father son',
  'Everything is good',
  'Got potential',
  'Guai guai',
  'Jaw drop',
  'Means got problem',
  'Muck around',
  'No choice',
  'Not funny not funny it\'s true',
  'One shot one kill',
  'Random rubbish',
  'Sai lah',
  'Sai understand?',
  'Slap the shit out of you',
  'Stupid or not?',
  'Tambah',
  'Tank',
  'The important thing in life',
  'The moral of the story is',
  'The point is',
  'The question i have now',
  'The question is',
  'The thing is that',
  'There is vision and then there is reality',
  'There\'s the truth and then there\'s the brutal truth',
  'These people are not stooopid ok?',
  'Timeout timeout!',
  'Very simple problem',
  'We talk offline',
  'Woohoo!',
  'You think they hire me because I handsome issit?',
  '\u5514\u6E05\u5514\u695A',
  '\u597D\u4E0D\u597D',
];
